### ISSUE TITLE
Dependency version conflicts

### ISSUE THREAD

**Issue by mproficiency** [M-M-Akash/Face_Recognition_System#3]
As per the description librarys are installed Enroll face py works just find
but the cpu version throws error in standard run, errors print_info=true and none

**Comment by mproficiency** [comment]
kindly share the exact dependencies or file version so i can test the same

**Comment by i-internet** [comment]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      -- Building for: Visual Studio 16 2019
      CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
        Compatibility with CMake < 3.5 has been removed from CMake.

        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.

        Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<32 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('C:\\Users\\SAM\\AppData\\Local\\Temp\\pip-install-w0n85dqz\\sentencepiece_8497856b28db4a0b9d53183e17c4adea\\setup.py',), "<pip-setuptools-caller>", "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<pip-setuptools-caller>", line 35, in <module>
        File "C:\Users\SAM\AppData\Local\Temp\pip-install-w0n85dqz\sentencepiece_8497856b28db4a0b9d53183e17c4adea\setup.py", line 128, in <module>
          subprocess.check_call([
          ~~~~~~~~~~~~~~~~~~~~~^^
              'cmake',
              ^^^^^^^^
          ...<6 lines>...
              '-DCMAKE_INSTALL_PREFIX=build\\root',
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ])
          ^^
        File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'sentencepiece', '-A', 'x64', '-B', 'build', '-DSPM_ENABLE_SHARED=OFF', '-DCMAKE_INSTALL_PREFIX=build\\root']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(base) C:\Users\SAM\Downloads\Face_Recognition_System>python face_recognition-gpu.py
Traceback (most recent call last):
  File "C:\Users\SAM\Downloads\Face_Recognition_System\face_recognition-gpu.py", line 1, in <module>
    import paddlehub as hub
ModuleNotFoundError: No module named 'paddlehub'

**Comment by M-M-Akash** [comment]
Thanks for reporting this, and sorry for the long silence.

You hit a real problem, and it has since become unfixable rather than merely awkward. **This project no longer uses PaddlePaddle** — the repo has been rewritten on `main` around insightface + ONNX Runtime, and the install issues go away with it.

### What was actually breaking

The dependency chain was `paddlepaddle → paddlehub → paddlenlp → sentencepiece`, pinned to old versions. `sentencepiece` has no prebuilt wheel for newer Python, so pip falls back to building it from source, which needs CMake and a C++ toolchain. On current systems that build now fails outright:

```
CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.
```

`sentencepiece` declares `cmake_minimum_required(VERSION <3.5)`, and **CMake 4.0 removed support for those values**. So `sentencepiece` fails to build → `paddlehub` never installs → `ModuleNotFoundError: No module named 'paddlehub'`. Issue #1 was the same class of problem from the other direction (`paddle.nn.layer.layers` moved inside Paddle itself).

### Why I stepped back from PaddlePaddle

- The chain above breaks every time CMake, Python or Paddle moves — and it broke repeatedly.
- Recognition required patching `insightface_paddle.py` so it would accept an external detector, which meant maintaining a **forked wheel** hosted on my own account. That fork's contents later disappeared, leaving no install path at all.
- [`littletomatodonkey/insight-face-paddle`](https://github.com/littletomatodonkey/insight-face-paddle) is effectively unmaintained.
- I re-checked the assumption that Paddle gave better CPU threading. It doesn't — `insightface_paddle.py` has no application-level threading at all, only `config.set_cpu_math_library_num_threads()` (default **1**) and MKLDNN. That is the same knob ONNX Runtime exposes as `intra_op_num_threads`, which the rewrite sets to the physical core count.

### What it is now

Six pip dependencies, all prebuilt wheels — no CMake, no Visual Studio, no compilation:

```
insightface  onnxruntime  opencv-python  numpy  fastapi  uvicorn
```

Detection is SCRFD and recognition is a MobileFaceNet-style embedder (the `buffalo_sc` bundle), running on CPU. It also gained passive anti-spoofing, a web dashboard and Docker support:

```bash
docker compose up web
# or
pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000
```


Closing as resolved by the rewrite.
